"use client";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, FileText, Gauge, Quote, Search, ShieldCheck, UserRoundCheck } from "lucide-react";
import LeadCapture from "@/components/LeadCapture";
import PressureScenario from "@/components/PressureScenario";
import ChatWidget from "@/components/ChatWidget";
import Footer from "@/components/Footer";
import s from "./page.module.css";

const steps=[["01","Map obligations","List active MCAs, withdrawal cadence, balances, and recent changes."],["02","Understand the operating impact","See how the payment structure interacts with payroll, inventory, taxes, and vendors."],["03","Compare realistic paths","Review what may be available, what is uncertain, and what documents still matter."],["04","Prepare the next move","Build a practical next-step plan for the business and the follow-up conversation."]];
const reviews=[
{name:"Restaurant owner",role:"Hospitality · sample review",image:"https://images.pexels.com/photos/3771839/pexels-photo-3771839.jpeg?auto=compress&cs=tinysrgb&w=1200",quote:"The review helped me understand which numbers and documents actually mattered before I made another move."},
{name:"Medical practice owner",role:"Healthcare · sample review",image:"https://images.pexels.com/photos/5452201/pexels-photo-5452201.jpeg?auto=compress&cs=tinysrgb&w=1200",quote:"It felt more like an analysis than a sales pitch. That made it easier to ask the right questions."},
{name:"Logistics operator",role:"Transportation · sample review",image:"https://images.pexels.com/photos/3760067/pexels-photo-3760067.jpeg?auto=compress&cs=tinysrgb&w=1200",quote:"I finally saw the stacked obligations as one operating problem instead of several unrelated payments."},
];
const guides=[["MCA BASICS","How MCA withdrawals affect operating cash","Understand the payment mechanics and why frequent debits can change the business week."],["STACKED POSITIONS","Why several advances should be mapped together","A combined view can reveal the real weekly burden more clearly than reviewing each agreement alone."],["DOCUMENT REVIEW","What to gather before an MCA consultation","Bank statements, agreements, balances, notices, and payment schedules can make the conversation more useful."]];

export default function Home(){
 const [open,setOpen]=useState(false); const [story,setStory]=useState(0); const active=reviews[story]; const move=(d:number)=>setStory((story+d+reviews.length)%reviews.length);
 return <main className={s.site}><header className={s.nav}><a className={s.brand} href="#top">MCA <b>DEBT CONSULTANT</b></a><nav className={s.navLinks}><a href="#method">Method</a><a href="#process">Process</a><a href="#resources">Resources</a><a href="#stories">Stories</a></nav><button className={s.navCta} onClick={()=>setOpen(true)}>Get my free MCA review</button></header>
 <section id="top" className={s.hero}><div className={`${s.wrap} ${s.heroGrid}`}><div className={s.copy}><span className={s.kicker}>KNOWLEDGE. STRATEGY. BUSINESS CLARITY.</span><h1>Understand the payment structure before choosing the next move.</h1><p>MCA Debt Consultant is an educational and advisory first step for business owners who want to understand withdrawal burden, organize the facts, and prepare for a more informed conversation.</p><div className={s.heroActions}><a className={s.primary} href="#review">Get my free MCA review <ArrowRight/></a><a className={s.secondary} href="#process">See how the review works</a></div><div className={s.trust}><span><ShieldCheck/>Confidential intake</span><span><Check/>Business-purpose focus</span><span><Check/>No guaranteed outcomes</span></div></div><PressureScenario/></div></section>
 <section id="review" className={s.session}><div className={`${s.wrap} ${s.sessionGrid}`}><div><span className={s.kicker}>FREE MCA REVIEW</span><h2>Start with two contact details. Explain the rest to a person.</h2><p>Name and phone are enough to begin. Additional business details are optional and can be discussed during the follow-up.</p></div><LeadCapture title="Get my free MCA review" button="Request my review" source="strategy"/></div></section>
 <section className={s.bodyText}><div className={`${s.wrap} ${s.bodyGrid}`}><div><span className={s.kicker}>WHAT THE REVIEW SHOULD CLARIFY</span><h2>See the business picture, not just the balance.</h2><p>An MCA problem is rarely only about the amount outstanding. The withdrawal cadence, stacked positions, average weekly revenue, fixed operating expenses, and any collection activity can all change what the business is experiencing day to day.</p><p>A useful review should help organize those facts, identify which questions still need answers, and make the next conversation more deliberate.</p></div><div className={s.checklist}><strong>Useful documents to gather</strong><ul><li>Recent bank statements</li><li>MCA agreements and estimated balances</li><li>Daily or weekly debit amounts</li><li>Notices or collection communications</li><li>Major operating obligations such as payroll and rent</li></ul></div></div></section>
 <section id="method" className={s.method}><div className={s.wrap}><div className={s.heading}><span className={s.kicker}>THE CONSULTANT VIEW</span><h2>Turn a confusing payment problem into a decision framework.</h2></div><div className={s.methodGrid}><article><Search/><small>01</small><h3>See the whole picture</h3><p>Review positions, debits, balances, and operating priorities together.</p></article><article><Gauge/><small>02</small><h3>Measure the withdrawal burden</h3><p>Understand what the current payment cadence is doing to available operating cash.</p></article><article><FileText/><small>03</small><h3>Review the documents</h3><p>Organize agreements, notices, and questions that may matter in the next conversation.</p></article><article><UserRoundCheck/><small>04</small><h3>Choose deliberately</h3><p>Compare realistic paths without relying on generic savings percentages or timelines.</p></article></div></div></section>
 <section id="process" className={s.process}><div className={s.wrap}><div className={s.heading}><span className={s.kicker}>ADVISORY ROADMAP</span><h2>From raw information to an organized next step.</h2><p>Each stage should make the visitor feel more informed, not simply move them through another marketing funnel.</p></div><div className={s.roadmap}>{steps.map(x=><article key={x[0]}><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></div></section>
 <section id="resources" className={s.resources}><div className={s.wrap}><div className={s.heading}><span className={s.kicker}>KNOWLEDGE CENTER</span><h2>Useful content for owners who are not ready to submit a form yet.</h2></div><div className={s.resourceGrid}>{guides.map(g=><a href="/insights" key={g[1]}><span>{g[0]}</span><h3>{g[1]}</h3><p>{g[2]}</p></a>)}</div></div></section>
 <section id="stories" className={s.stories}><div className={s.wrap}><div className={s.heading}><span className={s.kicker}>CLIENT PERSPECTIVE</span><h2>Credibility comes from clarity, not hype.</h2><p>Sample staging content only. Replace with client-approved reviews and photography before production.</p></div><div className={s.storyMain}><img src={active.image} alt={active.name}/><div className={s.storyCopy}><Quote/><p>“{active.quote}”</p><strong>{active.name}</strong><span>{active.role}</span></div></div><div className={s.storyControls}><button onClick={()=>move(-1)} aria-label="Previous story"><ArrowLeft size={18}/></button><div className={s.dots}>{reviews.map((_,i)=><button key={i} aria-label={`Story ${i+1}`} onClick={()=>setStory(i)} className={`${s.dot} ${i===story?s.active:""}`}/>)}</div><button onClick={()=>move(1)} aria-label="Next story"><ArrowRight size={18}/></button></div></div></section>
 <Footer/><ChatWidget/>{open&&<div className={s.modalBack} onClick={()=>setOpen(false)}><div className={s.modal} onClick={e=>e.stopPropagation()}><button className={s.modalX} onClick={()=>setOpen(false)}>×</button><LeadCapture title="Get my free MCA review" button="Request my review" source="strategy"/></div></div>}</main>
}
