import { notFound } from "next/navigation";
const pages:any={
'privacy-policy':['Privacy Policy',['We may collect information you submit through forms or chat, including name, phone number, optional business context, page source, and technical information used for security and analytics when enabled.','Information may be used to respond to inquiries, operate the website, prevent abuse, measure site performance, and route leads to authorized systems or service providers.','Do not submit confidential legal documents or highly sensitive personal information unless the company has approved a secure process for receiving them.']],
'terms-of-use':['Terms of Use',['This website is provided for general business information and inquiry purposes. Using the site does not enroll a business in a service or guarantee that any service will be offered.','Website content is not legal, tax, accounting, or financial advice. Business owners remain responsible for evaluating agreements and decisions with appropriate professional advisers.','Website content and third-party services may change without notice.']],
'legal-disclaimer':['Legal Disclaimer',['MCA Debt Consultant is not a lender, law firm, government agency, or court and does not provide legal representation through this website.','No statement or interactive example guarantees settlement, restructuring, payment reduction, creditor participation, timing, or any other result.','The cash-flow comparison shown on the homepage is illustrative only and should not be interpreted as a prediction, quote, or promised outcome.']],
'communication-consent':['Communication Consent',['When you check the contact-consent box and submit your information, you authorize calls and text messages regarding your business inquiry at the number you provided, including automated technology where permitted.','Consent is not a condition of purchase. Message and data rates may apply. Message frequency varies. Reply STOP to opt out of texts and HELP for assistance.']],
'cookie-policy':['Cookie Policy',['The staging website does not need advertising cookies to accept a lead. If analytics or advertising tools are enabled later, appropriate consent controls should be used before optional tracking is activated.','Essential technical storage may be used for security, preferences, and normal website operation.']]
};
export default async function Legal({params}:{params:Promise<{legal:string}>}){const{legal}=await params;const p=pages[legal];if(!p)notFound();return <main className="articlePage"><div className="wrap narrow"><a className="back" href="/">← Home</a><h1>{p[0]}</h1>{p[1].map((x:string)=><p key={x}>{x}</p>)}<p><strong>Staging draft:</strong> final language should be reviewed against the client’s actual services, states served, vendors, and communication practices before launch.</p></div></main>}
